services:
  - type: web
    name: dj-usb-server
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /opt/render/project/src/server/installers
      cp -r server/installers/* /opt/render/project/src/server/installers/
    startCommand: cd server && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
